#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-git-commit-id-plugin
Version  : 3.0.1
Release  : 1
URL      : https://github.com/git-commit-id/maven-git-commit-id-plugin/archive/v3.0.1.tar.gz
Source0  : https://github.com/git-commit-id/maven-git-commit-id-plugin/archive/v3.0.1.tar.gz
Source1  : https://repo1.maven.org/maven2/pl/project13/maven/git-commit-id-plugin/2.1.10/git-commit-id-plugin-2.1.10.jar
Source2  : https://repo1.maven.org/maven2/pl/project13/maven/git-commit-id-plugin/2.1.10/git-commit-id-plugin-2.1.10.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-3.0
Requires: mvn-maven-git-commit-id-plugin-data = %{version}-%{release}
Requires: mvn-maven-git-commit-id-plugin-license = %{version}-%{release}

%description
maven git commit id plugin
==================================
[![Join the chat at https://gitter.im/git-commit-id/maven-git-commit-id-plugin](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/git-commit-id/maven-git-commit-id-plugin?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
[![Build Status](https://secure.travis-ci.org/git-commit-id/maven-git-commit-id-plugin.svg?branch=master)](http://travis-ci.org/git-commit-id/maven-git-commit-id-plugin)
[![Coverage Status](https://coveralls.io/repos/github/git-commit-id/maven-git-commit-id-plugin/badge.svg?branch=master)](https://coveralls.io/github/git-commit-id/maven-git-commit-id-plugin?branch=master)
[![Maven Central](https://maven-badges.herokuapp.com/maven-central/pl.project13.maven/git-commit-id-plugin/badge.svg)](http://search.maven.org/#search|ga|1|pl.project13.maven)

%package data
Summary: data components for the mvn-maven-git-commit-id-plugin package.
Group: Data

%description data
data components for the mvn-maven-git-commit-id-plugin package.


%package license
Summary: license components for the mvn-maven-git-commit-id-plugin package.
Group: Default

%description license
license components for the mvn-maven-git-commit-id-plugin package.


%prep
%setup -q -n maven-git-commit-id-plugin-3.0.1

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-maven-git-commit-id-plugin
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-maven-git-commit-id-plugin/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/pl/project13/maven/git-commit-id-plugin/2.1.10
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/pl/project13/maven/git-commit-id-plugin/2.1.10/git-commit-id-plugin-2.1.10.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/pl/project13/maven/git-commit-id-plugin/2.1.10
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/pl/project13/maven/git-commit-id-plugin/2.1.10/git-commit-id-plugin-2.1.10.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/pl/project13/maven/git-commit-id-plugin/2.1.10/git-commit-id-plugin-2.1.10.jar
/usr/share/java/.m2/repository/pl/project13/maven/git-commit-id-plugin/2.1.10/git-commit-id-plugin-2.1.10.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-maven-git-commit-id-plugin/LICENSE
